/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#133157",
        "on-primary-fixed": "#001848",
        "tertiary-fixed-dim": "#4bddbb",
        "surface-dim": "#c8dbff",
        "primary-fixed": "#dae2ff",
        "surface-container-highest": "#d5e3ff",
        "on-error-container": "#93000a",
        "ocean-deep": "#002248",
        "on-secondary-container": "#596a00",
        "inverse-primary": "#b2c5ff",
        "secondary": "#556500",
        "secondary-container": "#d0ec56",
        "surface-variant": "#d5e3ff",
        "tertiary-container": "#00816a",
        "surface-bright": "#f9f9ff",
        "surface-container": "#e7eeff",
        "on-secondary-fixed-variant": "#3f4c00",
        "on-primary-fixed-variant": "#0040a2",
        "error": "#ba1a1a",
        "surface-container-low": "#f0f3ff",
        "on-secondary": "#ffffff",
        "primary": "#0050c8",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#6dfad7",
        "electric-sky": "#0567FA",
        "primary-fixed-dim": "#b2c5ff",
        "tertiary": "#006653",
        "surface-tint": "#0055d3",
        "surface-container-high": "#dee8ff",
        "on-primary-container": "#f7f7ff",
        "on-background": "#001b3c",
        "on-surface": "#001b3c",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#ecf1ff",
        "surface": "#f9f9ff",
        "outline-variant": "#c2c6d8",
        "lime-zest": "#BCD743",
        "primary-container": "#0567fa",
        "background": "#f9f9ff",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#424655",
        "secondary-fixed-dim": "#b7d23f",
        "on-tertiary-container": "#e0fff3",
        "on-tertiary-fixed": "#002019",
        "tropical-mint": "#44D7B6",
        "outline": "#727687",
        "on-error": "#ffffff",
        "secondary-fixed": "#d3ef59",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#181e00",
        "on-tertiary-fixed-variant": "#005142"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "base": "8px",
        "margin-desktop": "64px",
        "max-width": "1280px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-xl-mobile": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}
